name: 'swift-check-runner'
description: 'Check if macOS self-hosted runner is ready'
inputs:
  check-screen-is-unlocked:
    description: 'Check if screen is unlocked'
    required: false
    default: false
  should-cancel:
    description: 'Cancel workflow instead of failing'
    required: false
    default: true
outputs:
  reasons:
    description: 'Failing checks'
runs:
  using: 'node12'
  main: 'dist/index.js'
